package com.web.back.model;

import java.util.Date;

public class Menu {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MENU.MENU_ID
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    private Integer menuId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MENU.PARENT_MENU_ID
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    private Integer parentMenuId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MENU.MENU_NAME
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    private String menuName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MENU.WEIGHT
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    private Short weight;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MENU.ICONCLS
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    private String iconcls;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MENU.URL
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    private String url;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MENU.MENU_DESC
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    private String menuDesc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MENU.STATE
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    private String state;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MENU.STATE_DATE
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    private Date stateDate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MENU.MENU_ID
     *
     * @return the value of MENU.MENU_ID
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MENU.MENU_ID
     *
     * @param menuId the value for MENU.MENU_ID
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MENU.PARENT_MENU_ID
     *
     * @return the value of MENU.PARENT_MENU_ID
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public Integer getParentMenuId() {
        return parentMenuId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MENU.PARENT_MENU_ID
     *
     * @param parentMenuId the value for MENU.PARENT_MENU_ID
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public void setParentMenuId(Integer parentMenuId) {
        this.parentMenuId = parentMenuId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MENU.MENU_NAME
     *
     * @return the value of MENU.MENU_NAME
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MENU.MENU_NAME
     *
     * @param menuName the value for MENU.MENU_NAME
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MENU.WEIGHT
     *
     * @return the value of MENU.WEIGHT
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public Short getWeight() {
        return weight;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MENU.WEIGHT
     *
     * @param weight the value for MENU.WEIGHT
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public void setWeight(Short weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MENU.ICONCLS
     *
     * @return the value of MENU.ICONCLS
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public String getIconcls() {
        return iconcls;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MENU.ICONCLS
     *
     * @param iconcls the value for MENU.ICONCLS
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public void setIconcls(String iconcls) {
        this.iconcls = iconcls;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MENU.URL
     *
     * @return the value of MENU.URL
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MENU.URL
     *
     * @param url the value for MENU.URL
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MENU.MENU_DESC
     *
     * @return the value of MENU.MENU_DESC
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MENU.MENU_DESC
     *
     * @param menuDesc the value for MENU.MENU_DESC
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MENU.STATE
     *
     * @return the value of MENU.STATE
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MENU.STATE
     *
     * @param state the value for MENU.STATE
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MENU.STATE_DATE
     *
     * @return the value of MENU.STATE_DATE
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MENU.STATE_DATE
     *
     * @param stateDate the value for MENU.STATE_DATE
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }
}