package com.web.back.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class MenuExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table MENU
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table MENU
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MENU
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public MenuExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MENU
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    protected MenuExample(MenuExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MENU
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MENU
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MENU
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MENU
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MENU
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MENU
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MENU
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MENU
     *
     * @ibatorgenerated Fri Feb 10 16:01:19 CST 2012
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andMenuIdIsNull() {
            addCriterion("MENU_ID is null");
            return this;
        }

        public Criteria andMenuIdIsNotNull() {
            addCriterion("MENU_ID is not null");
            return this;
        }

        public Criteria andMenuIdEqualTo(Integer value) {
            addCriterion("MENU_ID =", value, "menuId");
            return this;
        }

        public Criteria andMenuIdNotEqualTo(Integer value) {
            addCriterion("MENU_ID <>", value, "menuId");
            return this;
        }

        public Criteria andMenuIdGreaterThan(Integer value) {
            addCriterion("MENU_ID >", value, "menuId");
            return this;
        }

        public Criteria andMenuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("MENU_ID >=", value, "menuId");
            return this;
        }

        public Criteria andMenuIdLessThan(Integer value) {
            addCriterion("MENU_ID <", value, "menuId");
            return this;
        }

        public Criteria andMenuIdLessThanOrEqualTo(Integer value) {
            addCriterion("MENU_ID <=", value, "menuId");
            return this;
        }

        public Criteria andMenuIdIn(List values) {
            addCriterion("MENU_ID in", values, "menuId");
            return this;
        }

        public Criteria andMenuIdNotIn(List values) {
            addCriterion("MENU_ID not in", values, "menuId");
            return this;
        }

        public Criteria andMenuIdBetween(Integer value1, Integer value2) {
            addCriterion("MENU_ID between", value1, value2, "menuId");
            return this;
        }

        public Criteria andMenuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("MENU_ID not between", value1, value2, "menuId");
            return this;
        }

        public Criteria andParentMenuIdIsNull() {
            addCriterion("PARENT_MENU_ID is null");
            return this;
        }

        public Criteria andParentMenuIdIsNotNull() {
            addCriterion("PARENT_MENU_ID is not null");
            return this;
        }

        public Criteria andParentMenuIdEqualTo(Integer value) {
            addCriterion("PARENT_MENU_ID =", value, "parentMenuId");
            return this;
        }

        public Criteria andParentMenuIdNotEqualTo(Integer value) {
            addCriterion("PARENT_MENU_ID <>", value, "parentMenuId");
            return this;
        }

        public Criteria andParentMenuIdGreaterThan(Integer value) {
            addCriterion("PARENT_MENU_ID >", value, "parentMenuId");
            return this;
        }

        public Criteria andParentMenuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PARENT_MENU_ID >=", value, "parentMenuId");
            return this;
        }

        public Criteria andParentMenuIdLessThan(Integer value) {
            addCriterion("PARENT_MENU_ID <", value, "parentMenuId");
            return this;
        }

        public Criteria andParentMenuIdLessThanOrEqualTo(Integer value) {
            addCriterion("PARENT_MENU_ID <=", value, "parentMenuId");
            return this;
        }

        public Criteria andParentMenuIdIn(List values) {
            addCriterion("PARENT_MENU_ID in", values, "parentMenuId");
            return this;
        }

        public Criteria andParentMenuIdNotIn(List values) {
            addCriterion("PARENT_MENU_ID not in", values, "parentMenuId");
            return this;
        }

        public Criteria andParentMenuIdBetween(Integer value1, Integer value2) {
            addCriterion("PARENT_MENU_ID between", value1, value2, "parentMenuId");
            return this;
        }

        public Criteria andParentMenuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PARENT_MENU_ID not between", value1, value2, "parentMenuId");
            return this;
        }

        public Criteria andMenuNameIsNull() {
            addCriterion("MENU_NAME is null");
            return this;
        }

        public Criteria andMenuNameIsNotNull() {
            addCriterion("MENU_NAME is not null");
            return this;
        }

        public Criteria andMenuNameEqualTo(String value) {
            addCriterion("MENU_NAME =", value, "menuName");
            return this;
        }

        public Criteria andMenuNameNotEqualTo(String value) {
            addCriterion("MENU_NAME <>", value, "menuName");
            return this;
        }

        public Criteria andMenuNameGreaterThan(String value) {
            addCriterion("MENU_NAME >", value, "menuName");
            return this;
        }

        public Criteria andMenuNameGreaterThanOrEqualTo(String value) {
            addCriterion("MENU_NAME >=", value, "menuName");
            return this;
        }

        public Criteria andMenuNameLessThan(String value) {
            addCriterion("MENU_NAME <", value, "menuName");
            return this;
        }

        public Criteria andMenuNameLessThanOrEqualTo(String value) {
            addCriterion("MENU_NAME <=", value, "menuName");
            return this;
        }

        public Criteria andMenuNameLike(String value) {
            addCriterion("MENU_NAME like", value, "menuName");
            return this;
        }

        public Criteria andMenuNameNotLike(String value) {
            addCriterion("MENU_NAME not like", value, "menuName");
            return this;
        }

        public Criteria andMenuNameIn(List values) {
            addCriterion("MENU_NAME in", values, "menuName");
            return this;
        }

        public Criteria andMenuNameNotIn(List values) {
            addCriterion("MENU_NAME not in", values, "menuName");
            return this;
        }

        public Criteria andMenuNameBetween(String value1, String value2) {
            addCriterion("MENU_NAME between", value1, value2, "menuName");
            return this;
        }

        public Criteria andMenuNameNotBetween(String value1, String value2) {
            addCriterion("MENU_NAME not between", value1, value2, "menuName");
            return this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("WEIGHT is null");
            return this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("WEIGHT is not null");
            return this;
        }

        public Criteria andWeightEqualTo(Short value) {
            addCriterion("WEIGHT =", value, "weight");
            return this;
        }

        public Criteria andWeightNotEqualTo(Short value) {
            addCriterion("WEIGHT <>", value, "weight");
            return this;
        }

        public Criteria andWeightGreaterThan(Short value) {
            addCriterion("WEIGHT >", value, "weight");
            return this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Short value) {
            addCriterion("WEIGHT >=", value, "weight");
            return this;
        }

        public Criteria andWeightLessThan(Short value) {
            addCriterion("WEIGHT <", value, "weight");
            return this;
        }

        public Criteria andWeightLessThanOrEqualTo(Short value) {
            addCriterion("WEIGHT <=", value, "weight");
            return this;
        }

        public Criteria andWeightIn(List values) {
            addCriterion("WEIGHT in", values, "weight");
            return this;
        }

        public Criteria andWeightNotIn(List values) {
            addCriterion("WEIGHT not in", values, "weight");
            return this;
        }

        public Criteria andWeightBetween(Short value1, Short value2) {
            addCriterion("WEIGHT between", value1, value2, "weight");
            return this;
        }

        public Criteria andWeightNotBetween(Short value1, Short value2) {
            addCriterion("WEIGHT not between", value1, value2, "weight");
            return this;
        }

        public Criteria andIconclsIsNull() {
            addCriterion("ICONCLS is null");
            return this;
        }

        public Criteria andIconclsIsNotNull() {
            addCriterion("ICONCLS is not null");
            return this;
        }

        public Criteria andIconclsEqualTo(String value) {
            addCriterion("ICONCLS =", value, "iconcls");
            return this;
        }

        public Criteria andIconclsNotEqualTo(String value) {
            addCriterion("ICONCLS <>", value, "iconcls");
            return this;
        }

        public Criteria andIconclsGreaterThan(String value) {
            addCriterion("ICONCLS >", value, "iconcls");
            return this;
        }

        public Criteria andIconclsGreaterThanOrEqualTo(String value) {
            addCriterion("ICONCLS >=", value, "iconcls");
            return this;
        }

        public Criteria andIconclsLessThan(String value) {
            addCriterion("ICONCLS <", value, "iconcls");
            return this;
        }

        public Criteria andIconclsLessThanOrEqualTo(String value) {
            addCriterion("ICONCLS <=", value, "iconcls");
            return this;
        }

        public Criteria andIconclsLike(String value) {
            addCriterion("ICONCLS like", value, "iconcls");
            return this;
        }

        public Criteria andIconclsNotLike(String value) {
            addCriterion("ICONCLS not like", value, "iconcls");
            return this;
        }

        public Criteria andIconclsIn(List values) {
            addCriterion("ICONCLS in", values, "iconcls");
            return this;
        }

        public Criteria andIconclsNotIn(List values) {
            addCriterion("ICONCLS not in", values, "iconcls");
            return this;
        }

        public Criteria andIconclsBetween(String value1, String value2) {
            addCriterion("ICONCLS between", value1, value2, "iconcls");
            return this;
        }

        public Criteria andIconclsNotBetween(String value1, String value2) {
            addCriterion("ICONCLS not between", value1, value2, "iconcls");
            return this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("URL is null");
            return this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("URL is not null");
            return this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("URL =", value, "url");
            return this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("URL <>", value, "url");
            return this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("URL >", value, "url");
            return this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("URL >=", value, "url");
            return this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("URL <", value, "url");
            return this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("URL <=", value, "url");
            return this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("URL like", value, "url");
            return this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("URL not like", value, "url");
            return this;
        }

        public Criteria andUrlIn(List values) {
            addCriterion("URL in", values, "url");
            return this;
        }

        public Criteria andUrlNotIn(List values) {
            addCriterion("URL not in", values, "url");
            return this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("URL between", value1, value2, "url");
            return this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("URL not between", value1, value2, "url");
            return this;
        }

        public Criteria andMenuDescIsNull() {
            addCriterion("MENU_DESC is null");
            return this;
        }

        public Criteria andMenuDescIsNotNull() {
            addCriterion("MENU_DESC is not null");
            return this;
        }

        public Criteria andMenuDescEqualTo(String value) {
            addCriterion("MENU_DESC =", value, "menuDesc");
            return this;
        }

        public Criteria andMenuDescNotEqualTo(String value) {
            addCriterion("MENU_DESC <>", value, "menuDesc");
            return this;
        }

        public Criteria andMenuDescGreaterThan(String value) {
            addCriterion("MENU_DESC >", value, "menuDesc");
            return this;
        }

        public Criteria andMenuDescGreaterThanOrEqualTo(String value) {
            addCriterion("MENU_DESC >=", value, "menuDesc");
            return this;
        }

        public Criteria andMenuDescLessThan(String value) {
            addCriterion("MENU_DESC <", value, "menuDesc");
            return this;
        }

        public Criteria andMenuDescLessThanOrEqualTo(String value) {
            addCriterion("MENU_DESC <=", value, "menuDesc");
            return this;
        }

        public Criteria andMenuDescLike(String value) {
            addCriterion("MENU_DESC like", value, "menuDesc");
            return this;
        }

        public Criteria andMenuDescNotLike(String value) {
            addCriterion("MENU_DESC not like", value, "menuDesc");
            return this;
        }

        public Criteria andMenuDescIn(List values) {
            addCriterion("MENU_DESC in", values, "menuDesc");
            return this;
        }

        public Criteria andMenuDescNotIn(List values) {
            addCriterion("MENU_DESC not in", values, "menuDesc");
            return this;
        }

        public Criteria andMenuDescBetween(String value1, String value2) {
            addCriterion("MENU_DESC between", value1, value2, "menuDesc");
            return this;
        }

        public Criteria andMenuDescNotBetween(String value1, String value2) {
            addCriterion("MENU_DESC not between", value1, value2, "menuDesc");
            return this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return this;
        }

        public Criteria andStateIn(List values) {
            addCriterion("STATE in", values, "state");
            return this;
        }

        public Criteria andStateNotIn(List values) {
            addCriterion("STATE not in", values, "state");
            return this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return this;
        }

        public Criteria andStateDateIsNull() {
            addCriterion("STATE_DATE is null");
            return this;
        }

        public Criteria andStateDateIsNotNull() {
            addCriterion("STATE_DATE is not null");
            return this;
        }

        public Criteria andStateDateEqualTo(Date value) {
            addCriterionForJDBCDate("STATE_DATE =", value, "stateDate");
            return this;
        }

        public Criteria andStateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("STATE_DATE <>", value, "stateDate");
            return this;
        }

        public Criteria andStateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("STATE_DATE >", value, "stateDate");
            return this;
        }

        public Criteria andStateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("STATE_DATE >=", value, "stateDate");
            return this;
        }

        public Criteria andStateDateLessThan(Date value) {
            addCriterionForJDBCDate("STATE_DATE <", value, "stateDate");
            return this;
        }

        public Criteria andStateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("STATE_DATE <=", value, "stateDate");
            return this;
        }

        public Criteria andStateDateIn(List values) {
            addCriterionForJDBCDate("STATE_DATE in", values, "stateDate");
            return this;
        }

        public Criteria andStateDateNotIn(List values) {
            addCriterionForJDBCDate("STATE_DATE not in", values, "stateDate");
            return this;
        }

        public Criteria andStateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("STATE_DATE between", value1, value2, "stateDate");
            return this;
        }

        public Criteria andStateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("STATE_DATE not between", value1, value2, "stateDate");
            return this;
        }
    }
}