package com.web.back.model;

import java.util.Date;

public class Staff {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column STAFF.STAFF_ID
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    private Integer staffId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column STAFF.STAFF_CODE
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    private String staffCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column STAFF.PASSWD
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    private String passwd;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column STAFF.STAFF_NAME
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    private String staffName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column STAFF.STAFF_DESC
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    private String staffDesc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column STAFF.ORG_ID
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    private Integer orgId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column STAFF.BSS_ORG_ID
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    private Integer bssOrgId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column STAFF.WORK_GROUP_ID
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    private Integer workGroupId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column STAFF.STATE
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    private String state;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column STAFF.STATE_DATE
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    private Date stateDate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column STAFF.STAFF_ID
     *
     * @return the value of STAFF.STAFF_ID
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column STAFF.STAFF_ID
     *
     * @param staffId the value for STAFF.STAFF_ID
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column STAFF.STAFF_CODE
     *
     * @return the value of STAFF.STAFF_CODE
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public String getStaffCode() {
        return staffCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column STAFF.STAFF_CODE
     *
     * @param staffCode the value for STAFF.STAFF_CODE
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public void setStaffCode(String staffCode) {
        this.staffCode = staffCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column STAFF.PASSWD
     *
     * @return the value of STAFF.PASSWD
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column STAFF.PASSWD
     *
     * @param passwd the value for STAFF.PASSWD
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column STAFF.STAFF_NAME
     *
     * @return the value of STAFF.STAFF_NAME
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column STAFF.STAFF_NAME
     *
     * @param staffName the value for STAFF.STAFF_NAME
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column STAFF.STAFF_DESC
     *
     * @return the value of STAFF.STAFF_DESC
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public String getStaffDesc() {
        return staffDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column STAFF.STAFF_DESC
     *
     * @param staffDesc the value for STAFF.STAFF_DESC
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public void setStaffDesc(String staffDesc) {
        this.staffDesc = staffDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column STAFF.ORG_ID
     *
     * @return the value of STAFF.ORG_ID
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column STAFF.ORG_ID
     *
     * @param orgId the value for STAFF.ORG_ID
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column STAFF.BSS_ORG_ID
     *
     * @return the value of STAFF.BSS_ORG_ID
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public Integer getBssOrgId() {
        return bssOrgId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column STAFF.BSS_ORG_ID
     *
     * @param bssOrgId the value for STAFF.BSS_ORG_ID
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public void setBssOrgId(Integer bssOrgId) {
        this.bssOrgId = bssOrgId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column STAFF.WORK_GROUP_ID
     *
     * @return the value of STAFF.WORK_GROUP_ID
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public Integer getWorkGroupId() {
        return workGroupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column STAFF.WORK_GROUP_ID
     *
     * @param workGroupId the value for STAFF.WORK_GROUP_ID
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public void setWorkGroupId(Integer workGroupId) {
        this.workGroupId = workGroupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column STAFF.STATE
     *
     * @return the value of STAFF.STATE
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column STAFF.STATE
     *
     * @param state the value for STAFF.STATE
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column STAFF.STATE_DATE
     *
     * @return the value of STAFF.STATE_DATE
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column STAFF.STATE_DATE
     *
     * @param stateDate the value for STAFF.STATE_DATE
     *
     * @ibatorgenerated Fri Feb 10 16:00:36 CST 2012
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }
}